apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-stack
namespace: monitoring
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "73.2.0"
    releaseName: prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml
resources:
  - servicemonitors.yaml
  - http-routes.yaml
  - alerting-rules.yaml
patches:
  - path: resource-patches.yaml
    target:
      kind: StatefulSet
      name: prometheus-prometheus-stack-kube-prom-prometheus
