apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-nielszwemmer
  namespace: gateway
spec:
  dnsNames:
    - "*.nielszwemmer.nl"
    - nielszwemmer.nl
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-nielszwemmer
  usages:
    - digital signature
    - key encipherment