
driver:
  name: nfs.csi.k8s.io
  replicas: 2

storageClasses:
- name: nfs-csi
  defaultClass: false
  parameters:
    server: 172.24.60.133
    share: /mnt/generaltank/k8s/
  mountOptions:
    - nfsvers=4.1

csiDriver:
  name: nfs.csi.k8s.io
  attachRequired: false
  fsGroupPolicy: File

kubeletDir: /var/lib/kubelet