apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-components
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git # Corrected the repo URL
        revision: HEAD
        directories:
          - path: monitoring/argocd/applications/*
  template:
    metadata:
      labels:
        type: monitoring
      name: '{{path.basename}}'
    spec:
      project: monitoring
      source:
        # Use the same Kustomize+Helm plugin as other appsets
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git # Corrected the repo URL
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        # All monitoring components go into the 'monitoring' namespace
        namespace: 'monitoring'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false # The namespace is created separately
          - ServerSideApply=true
