# rbac.yaml
# Grant the prometheus admission webhook service account access to get secrets in the argocd namespace.
# This is required by the create-admission job to pass successfully.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-admission-secret-reader
  namespace: argocd # This Role grants permissions within the 'argocd' namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Ensure this is created before the job runs
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-admission-secret-reader-binding
  namespace: argocd # This RoleBinding applies within the 'argocd' namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Ensure this is created before the job runs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-admission-secret-reader # The Role being granted
subjects:
  - kind: ServiceAccount
    name: kube-prometheus-stack-admission # The ServiceAccount receiving the permission
    namespace: monitoring # The namespace where the ServiceAccount lives 
